### ISSUE TITLE
Sir how can i replace  the relative parameters and data to Sir how can i replace  the relative parameters and data to identify my own dataset? 

### ISSUE THREAD

**Issue by ZdaZda** [j05t/dbclf#2]
which files  should i modify？

**Comment by j05t** [comment]
Category names are stored in https://github.com/j05t/dbclf/blob/master/res/values/strings.xml in the same order the model outputs predicted classes.  The Inception v3 model (assets/stripped.pb) is configured and loaded in https://github.com/j05t/dbclf/blob/master/src/com/jstappdev/dbclf/ClassifierActivity.java. You may need to adapt INPUT_NAME  and OUTPUT_NAME. The app should work fine with any MobileNet or Inception v3 model. Please note that the code is based on TensorFlow 1.8 and may not work for TensorFlow 2.

**Comment by raheelrehman** [comment]
Can you tell me the way, you use to create dataset? because the matching version is necessary, and right now, tensorflow 1.8 is not working properly, tensorflow 2 is available now, so what should I do, in case, if I want to change the dataset.

**Comment by j05t** [comment]
I would recommend using the tensorflow 2 Android camera demo at
https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/android/README.md
as a base and transfer learn a pretrained model to your dataset using
latest tensorflow.
