### ISSUE TITLE
I want to change the dataset within the app, but I am confused how to do that.

### ISSUE THREAD

**Issue by raheelrehman** [j05t/dbclf#3]
Hi there, I have tried several things, but I couldn't be able to use python with tensorflow to train my model. The model that you used in your code is old, I also tried ML Kit to train model and then try to use it in the code, but didn't work, Can you tell me the way to train my own pictures. So, that I would be able to replace all the relevant things and get the result that I can see in your code perfectly. 
I am not that much familiar with tensorflow, that's why I am seeing error. I hope you will understand my situation and help me accordingly. Waiting for your response.

**Comment by j05t** [comment]
Hi,

I would recommend using the <a href="https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/android/README.md">TensorFlow Lite demo application</a> as a base, and to <a href="https://www.tensorflow.org/tutorials/images/transfer_learning">transfer learn</a> a model pretrained on ImageNet to your target dataset. This <a href="https://www.tensorflow.org/lite/tutorials/model_maker_image_classification">tutorial</a> should help you getting started.
